# Data Analyst au sein de la FAO

lien du brief : https://simplonline.co/briefs/688fc302-e4d4-4324-8904-f22316c31713

lien du dossier git : https://github.com/data-IA-2023/Groupe-3

Vous venez d'intégrer la FAO (Food and Agriculture Organization of the United Nations). BRAVO !!!!!!
Vous allez mener votre première mission en analysant les données mondiales de production agricole, d'alimentation et de nutrition.

**Livrables**

* Un dépôt Github
* Un notebook **fonctionnel, documenté et commenté**
* Une présentation écrite et orale résumant vos travaux, votre analyse et vos recommandations

**Contexte du projet**

* Au sein du service Data Analytics and Prospective de la FAO, vous êtes en charge d'analyser les données produites par les Nations Unies.

* Ces analyses conduisent à des rapports de synthèse à destination des décideurs.

* Pour êtes également en charge de la partie Prospective, c'est à dire donner des tendances et des évolutions probables quant à la production agricole, à l'alimentation et la nutrition mondiales.

**Ressource(s)**

FAO - Wikipedia : https://fr.wikipedia.org/wiki/Organisation_des_Nations_unies_pour_l'alimentation_et_l'agriculture

FAOSTAT : https://www.fao.org/faostat/fr/#home

Les données FAO 2013 : https://github.com/remijul/dataset/tree/master/fao_2013

## Partie extraction des données

In [ ]:
import pandas as pd
import numpy as np

chemein_fichier = "https://raw.githubusercontent.com/remijul/dataset/master/fao_2013/FAOSTAT_2013_animal.csv"

df = pd.read_csv(chemein_fichier, sep=',',on_bad_lines='skip')
df

,Code Domaine,Domaine,Code Pays,Pays,Code Élément,Élément,Code Produit,Produit,Code Année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Bilans Alimentaires,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,2013,Milliers de tonnes,134.00,S,Données standardisées
1,FBS,Bilans Alimentaires,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,2013,Milliers de tonnes,6.00,S,Données standardisées
2,FBS,Bilans Alimentaires,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
3,FBS,Bilans Alimentaires,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
4,FBS,Bilans Alimentaires,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37161,FBS,Bilans Alimentaires,351,Chine,5142,Nourriture,2775,Plantes Aquatiques,2013,2013,Milliers de tonnes,13086.00,A,"Agrégat, peut inclure des données officielles,..."
37162,FBS,Bilans Alimentaires,351,Chine,645,Disponibilité alimentaire en quantité (kg/pers...,2775,Plantes Aquatiques,2013,2013,kg,9.24,Fc,Donnée calculée
37163,FBS,Bilans Alimentaires,351,Chine,664,Disponibilité alimentaire (Kcal/personne/jour),2775,Plantes Aquatiques,2013,2013,Kcal/personne/jour,9.00,Fc,Donnée calculée
37164,FBS,Bilans Alimentaires,351,Chine,674,Disponibilité de protéines en quantité (g/pers...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.69,Fc,Donnée calculée
37165,FBS,Bilans Alimentaires,351,Chine,684,Disponibilité de matière grasse en quantité (g...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.04,Fc,Donnée calculée

In [1]:
import pandas as pd
import numpy as np

chemein_fichier = "fao_2013/FAOSTAT_2013_animal.csv"

df = pd.read_csv(chemein_fichier, sep=',',on_bad_lines='skip')
df

,Code Domaine,Domaine,Code Pays,Pays,Code Élément,Élément,Code Produit,Produit,Code Année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Bilans Alimentaires,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,2013,Milliers de tonnes,134.00,S,Données standardisées
1,FBS,Bilans Alimentaires,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,2013,Milliers de tonnes,6.00,S,Données standardisées
2,FBS,Bilans Alimentaires,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
3,FBS,Bilans Alimentaires,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
4,FBS,Bilans Alimentaires,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37161,FBS,Bilans Alimentaires,351,Chine,5142,Nourriture,2775,Plantes Aquatiques,2013,2013,Milliers de tonnes,13086.00,A,"Agrégat, peut inclure des données officielles,..."
37162,FBS,Bilans Alimentaires,351,Chine,645,Disponibilité alimentaire en quantité (kg/pers...,2775,Plantes Aquatiques,2013,2013,kg,9.24,Fc,Donnée calculée
37163,FBS,Bilans Alimentaires,351,Chine,664,Disponibilité alimentaire (Kcal/personne/jour),2775,Plantes Aquatiques,2013,2013,Kcal/personne/jour,9.00,Fc,Donnée calculée
37164,FBS,Bilans Alimentaires,351,Chine,674,Disponibilité de protéines en quantité (g/pers...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.69,Fc,Donnée calculée
37165,FBS,Bilans Alimentaires,351,Chine,684,Disponibilité de matière grasse en quantité (g...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.04,Fc,Donnée calculée

## Partie netoyage des données

In [1]:
import pandas as pd

# File paths
animal_file = 'fao_2013/FAOSTAT_2013_animal.csv'
cereal_file = 'fao_2013/FAOSTAT_2013_cereal.csv'
population_file = 'fao_2013/FAOSTAT_2013_population.csv'
sous_alimentation_file = 'fao_2013/FAOSTAT_2013_sous_alimentation.csv'
vegetal_file = 'fao_2013/FAOSTAT_2013_vegetal.csv'

# Load original data into DataFrames
animal_original_df = pd.read_csv(animal_file)
cereal_original_df = pd.read_csv(cereal_file)
population_original_df = pd.read_csv(population_file)
sous_alimentation_original_df = pd.read_csv(sous_alimentation_file)
vegetal_original_df = pd.read_csv(vegetal_file)

# Load cleaned data into DataFrames
cleaned_animal_df = pd.read_csv('cleaned_animal.csv')
cleaned_cereal_df = pd.read_csv('cleaned_cereal.csv')
cleaned_population_df = pd.read_csv('cleaned_population.csv')
cleaned_sous_alimentation_df = pd.read_csv('cleaned_sous_alimentation.csv')
cleaned_vegetal_df = pd.read_csv('cleaned_vegetal.csv')

# Identify and display rows removed during cleaning
def display_removed_rows(original_df, cleaned_df):
    removed_rows = pd.concat([original_df, cleaned_df]).drop_duplicates(keep=False)# pd.concat([original_df, cleaned_df]): This function concatenates the rows of both original_df and cleaned_df DataFrames along the rows (axis=0). This creates a new DataFrame with all the rows from both original and cleaned DataFrames.
    print(removed_rows)

# Display removed rows for each dataset
print("Removed rows in Animal DataFrame:")
display_removed_rows(animal_original_df, cleaned_animal_df)

print("\nRemoved rows in Cereal DataFrame:")
display_removed_rows(cereal_original_df, cleaned_cereal_df)

print("\nRemoved rows in Population DataFrame:")
display_removed_rows(population_original_df, cleaned_population_df)

print("\nRemoved rows in Sous Alimentation DataFrame:")
display_removed_rows(sous_alimentation_original_df, cleaned_sous_alimentation_df)

print("\nRemoved rows in Vegetal DataFrame:")
display_removed_rows(vegetal_original_df, cleaned_vegetal_df)


#import pandas as pd: This line imports the pandas library and gives it an alias pd.

#animal_file = 'fao_2013/FAOSTAT_2013_animal.csv': This line defines the file path for the animal dataset.

#animal_original_df = pd.read_csv(animal_file): This line reads the original animal dataset into a pandas DataFrame named animal_original_df.

#Similar steps are repeated for other datasets (cereal, population, sous_alimentation, and vegetal).

#cleaned_animal_df = pd.read_csv('cleaned_animal.csv'): This line reads the cleaned animal dataset into a DataFrame.

#Similar steps are repeated for other cleaned datasets.

#def display_removed_rows(original_df, cleaned_df):: This line defines a function named display_removed_rows that takes two DataFrames (original_df and cleaned_df) as arguments.

#removed_rows = pd.concat([original_df, cleaned_df]).drop_duplicates(keep=False): This line concatenates the original and cleaned DataFrames, and then removes duplicate rows to identify which rows were removed during cleaning.

#print(removed_rows): This line prints the DataFrame containing rows that were removed during cleaning.

#Finally, the script calls the display_removed_rows function for each dataset (animal, cereal, population, sous_alimentation, vegetal) to show which rows were removed during the cleaning process.

#If the output shows any rows, those are the rows that were present in the original dataset but were removed during the cleaning process. If the output is empty, it means no rows were removed during cleaning.

Removed rows in Animal DataFrame:
Empty DataFrame
Columns: [Code Domaine, Domaine, Code Pays, Pays, Code Élément, Element, Code Produit, Produit, Code Année, Année, Unité, Valeur, Symbole, Description du Symbole]
Index: []

Removed rows in Cereal DataFrame:
Empty DataFrame
Columns: [Code Domaine, Domaine, Code Pays, Pays, Code Élément, Élément, Code Produit, Produit, Code Année, Année, Unité, Valeur, Symbole, Description du Symbole]
Index: []

Removed rows in Population DataFrame:
    Domain Code               Domain  Country Code  \
0           FBS  Food Balance Sheets             2
1           FBS  Food Balance Sheets             3
2           FBS  Food Balance Sheets             4
3           FBS  Food Balance Sheets             7
4           FBS  Food Balance Sheets             8
..          ...                  ...           ...
169         FBS  Food Balance Sheets           236
170         FBS  Food Balance Sheets           237
171         FBS  Food Balance Sheets           249
172         FBS  Food Balance Sheets           251
173         FBS  Food Balance Sheets           181

                                Country  Element Code  \
0                           Afghanistan           511
1                               Albania           511
2                               Algeria           511
3                                Angola           511
4                   Antigua and Barbuda           511
..                                  ...           ...
169  Venezuela (Bolivarian Republic of)           511
170                            Viet Nam           511
171                               Yemen           511
172                              Zambia           511
173                            Zimbabwe           511

                           Element  Item Code        Item  Year Code  Year  \
0    Total Population - Both sexes       2501  Population       2013  2013
1    Total Population - Both sexes       2501  Population       2013  2013
2    Total Population - Both sexes       2501  Population       2013  2013
3    Total Population - Both sexes       2501  Population       2013  2013
4    Total Population - Both sexes       2501  Population       2013  2013
..                             ...        ...         ...        ...   ...
169  Total Population - Both sexes       2501  Population       2013  2013
170  Total Population - Both sexes       2501  Population       2013  2013
171  Total Population - Both sexes       2501  Population       2013  2013
172  Total Population - Both sexes       2501  Population       2013  2013
173  Total Population - Both sexes       2501  Population       2013  2013

             Unit  Value Flag Flag Description
0    1000 persons  30552  NaN    Official data
1    1000 persons   3173  NaN    Official data
2    1000 persons  39208  NaN    Official data
3    1000 persons  21472  NaN    Official data
4    1000 persons     90  NaN    Official data
..            ...    ...  ...              ...
169  1000 persons  30405  NaN    Official data
170  1000 persons  91680  NaN    Official data
171  1000 persons  24407  NaN    Official data
172  1000 persons  14539  NaN    Official data
173  1000 persons  14150  NaN    Official data

[174 rows x 14 columns]

Removed rows in Sous Alimentation DataFrame:
    Code Domaine                             Domaine  Code zone  \
4             FS  Données de la sécurité alimentaire         79
5             FS  Données de la sécurité alimentaire          6
7             FS  Données de la sécurité alimentaire          8
11            FS  Données de la sécurité alimentaire         10
12            FS  Données de la sécurité alimentaire         11
..           ...                                 ...        ...
194           FS  Données de la sécurité alimentaire        223
195           FS  Données de la sécurité alimentaire        227
196           FS  Données de la sécurité alimentaire        230
197           FS  Données de la sécurité alimentaire        234
198           FS  Données de la sécurité alimentaire        155

                   Zone  Code Élément Élément  Code Produit  \
4             Allemagne          6132  Valeur         21001
5               Andorre          6132  Valeur         21001
7    Antigua-et-Barbuda          6132  Valeur         21001
11            Australie          6132  Valeur         21001
12             Autriche          6132  Valeur         21001
..                  ...           ...     ...           ...
194             Turquie          6132  Valeur         21001
195              Tuvalu          6132  Valeur         21001
196             Ukraine          6132  Valeur         21001
197             Uruguay          6132  Valeur         21001
198             Vanuatu          6132  Valeur         21001

                                               Produit  Code année      Année  \
4    Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014
5    Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014
7    Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014
11   Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014
12   Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014
..                                                 ...         ...        ...
194  Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014
195  Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014
196  Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014
197  Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014
198  Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014

        Unité  Valeur Symbole  \
4    millions     NaN      <2
5    millions     NaN      NV
7    millions     NaN      NV
11   millions     NaN    <0.6
12   millions     NaN    <0.2
..        ...     ...     ...
194  millions     NaN    <1.9
195  millions     NaN      NV
196  millions     NaN    <1.1
197  millions     NaN    <0.1
198  millions     NaN    <0.1

                                Description du Symbole
4    Moins de 2 millions de personnes sont sous-ali...
5                                       Non disponible
7                                       Non disponible
11     Moins de 600 000 personnes sont sous-alimentées
12     Moins de 200 000 personnes sont sous-alimentées
..                                                 ...
194  Moins de 1.9 million de personnes sont sous-al...
195                                     Non disponible
196  Moins de 1.1 million de personnes sont sous-al...
197    Moins de 100 000 personnes sont sous-alimentées
198    Moins de 100 000 personnes sont sous-alimentées

[107 rows x 14 columns]

Removed rows in Vegetal DataFrame:
Empty DataFrame
Columns: [Code Domaine, Domaine, Code Pays, Pays, Code Élément, Element, Code Produit, Produit, Code Année, Année, Unité, Valeur, Symbole, Description du Symbole]
Index: []

In [3]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('fao_2013/FAOSTAT_2013_population.csv')

# Find the index of the last occurrence of 'China'
last_china_index = df[df['Country'] == 'China'].index[-1]

# Drop the row with the last occurrence of 'China'
df_filtered = df.drop(last_china_index)

# Save the filtered data to a new CSV file
df_filtered.to_csv('fao_2013/FAOSTAT_2013_population_filtered.csv', index=False)

## Partie traitement des données

### 1 - Analyses descriptives et exploratoire des données

Il s’agit ici de réaliser des analyses descriptives statistiques et graphiques sur les différentes variables des jeux de données :

    • Analyses univariées
    • Analyses bi-variées
    • Analyses multi-variées

Réaliser également des analyses exploratoires sur les différentes variables

Il s’agit ici de réaliser des analyses descriptives statistiques et graphiques sur les différentes variables des jeux de données :
    • Analyses univariées
    • Analyses bi-variées
    • Analyses multi-variées
Réaliser également des analyses exploratoires sur les différentes variables

In [1]:
'''import pandas as pd # Import Pandas for data manipulation and analysis   
# First, I loaded a dataset about animal products in 2013 using Pandas.
import numpy as np # Import NumPy for numerical operations

# Load the dataset
df = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv')

# Calculate the counts of each unique value in the 'Produit' column
produit_counts = df['Produit'].value_counts()

# Find the mode (most common value) of the 'Produit' column
produit_mode = df['Produit'].mode().values[0]

# Output the Univariate Analysis results for 'Produit'
print("Univariate Analysis - Produit Variable:")
print("\nProduit Counts:")
print(produit_counts)
print("\nProduit Mode:")
print(produit_mode)



# Read the CSV file and create a DataFrame named 'df'
df = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv')

# Bivariate Analysis - Relationship between 'Année' and 'Valeur'

# Calculate the correlation coefficient between 'Année' and 'Valeur'
correlation_coefficient = df['Année'].corr(df['Valeur'])

# Calculate the mean and median for 'Année' and 'Valeur'
mean_annee = df['Année'].mean()
median_annee = df['Année'].median()
mean_valeur = df['Valeur'].mean()
median_valeur = df['Valeur'].median()

# Output the Bivariate Analysis results including mean and median
print("Bivariate Analysis - Relationship between Année and Valeur:")
print("\nCorrelation Coefficient:", correlation_coefficient)  # quantify the association between variables or features of a dataset
print("\nMean Année:", mean_annee)
print("Median Année:", median_annee)
print("\nMean Valeur:", mean_valeur)
print("Median Valeur:", median_valeur)'''

fao_2013/FAOSTAT_2013_vegetal.csv
fao_2013/FAOSTAT_2013_population_filtered.csv

Univariate Analysis - Produit Variable:

Produit Counts:
Produit
Lait - Excl Beurre          2128
Poissons Pelagiques         1962
Oeufs                       1959
Graisses Animales Crue      1873
Poissons Eau Douce          1803
Crustacés                   1802
Poissons Marins, Autres     1797
Perciform                   1778
Viande de Bovins            1756
Mollusques, Autres          1700
Viande de Volailles         1693
Cephalopodes                1691
Abats Comestible            1678
Viande de Suides            1676
Huiles de Poissons          1637
Viande, Autre               1629
Beurre, Ghee                1593
Viande d'Ovins/Caprins      1562
Plantes Aquatiques          1483
Huiles de Foie de Poisso    1364
Crème                       1317
Animaux Aquatiques Autre    1258
Viande de Anim Aquatiq        27
Name: count, dtype: int64

Produit Mode:
Lait - Excl Beurre
Bivariate Analysis - Relationship between Année and Valeur:

Correlation Coefficient: nan

Mean Année: 2013.0
Median Année: 2013.0

Mean Valeur: 148.29164693537103
Median Valeur: 1.0

/home/codespace/.python/current/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/codespace/.python/current/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

### 2 - Etude guidée n°1

Il s’agit ici de répondre à toutes les questions ci-dessous.


Question 1 : Nombre d'humains sur la planète
Calculez le nombre total d’humains sur la planète.
Critiquez votre résultat. En cas d’anomalie, analysez et effectuer les corrections nécessaires.
Donnez le résultat de votre calcul pour l'année 2013.

In [8]:
'''import pandas as pd
population_df = pd.read_csv('fao_2013/FAOSTAT_2013_population.csv')

 #Create a new DataFrame called population_2013 by filtering population_df based on the 'Year' column. 
#It selects only the rows where the 'Year' is equal to 2013.
population_2013 = population_df[population_df['Year'] == 2013]

#Calculate the sum of the 'Value' column in the population_2013 DataFrame. 
#In this context, 'Value' likely represents the population count. The result is stored in the variable total_human_population.
total_human_population = population_2013['Value'].sum()
print("Total number of humans on the planet in 2013:", total_human_population)'''








import pandas as pd

# Read the CSV file
population_df = pd.read_csv('fao_2013/FAOSTAT_2013_population.csv')

# Find the index of the last occurrence of 'China'
#last_china_index: This variable holds the index of the last occurrence of the country 'China' in the 'Country' column of the DataFrame. 
#It is found using population_df[population_df['Country'] == 'China'].index[-1].
last_china_index = population_df[population_df['Country'] == 'China'].index[-1]

# Exclude the last occurrence of 'China'
 #  population_df: This is the original DataFrame that contains the population data.



#population_df.drop(last_china_index): This part uses the drop method to create a new DataFrame called filtered_population_df. 
#The drop method removes the row specified by the index last_china_index from the original DataFrame (population_df).
# The result is a new DataFrame without the row corresponding to the last occurrence of 'China'.
filtered_population_df = population_df.drop(last_china_index)

# Create a new DataFrame called population_2013 by filtering filtered_population_df based on the 'Year' column.
# It selects only the rows where the 'Year' is equal to 2013.
population_2013 = filtered_population_df[filtered_population_df['Year'] == 2013]

# Calculate the sum of the 'Value' column in the population_2013 DataFrame.
# In this context, 'Value' likely represents the population count.
# The result is stored in the variable total_human_population.
total_human_population = population_2013['Value'].sum()

print("Total number of humans on the planet in 2013 (excluding the last occurrence of China):", total_human_population)

Total number of humans on the planet in 2013 (excluding the last occurrence of China): 6997326

#### Question 2 : Redondances
Identifiez ces redondances, en donnant votre réponse sous forme de formule mathématique (pas besoin de coder ici).
C'est une équation à 3 termes de type (a_1 + a2 + [...] = b_1 + b_2 + [...] = c_1 + c_2 + [...]) ) faisant intervenir chacune des 11 quantités données ci dessus.
Illustrez cette équation avec l'exemple du blé en France.

In [ ]:
#let's define the quantities mentioned in the data:
 
#Let assume
#P represent the production of wheat in France.
#I represent the quantity of wheat imported to France.
#V represent the variation in stock of wheat in France.
#E represent the quantity of wheat exported from France.
#DI represent the domestic availability of wheat in France.
#AA represent the quantity of wheat used as animal feed.
#S represent the quantity of wheat used for seeds.
#L represent the quantity of wheat lost during processing.
#T represent the quantity of wheat used for industrial processing or treatment.
#AU represent the quantity of wheat used for other purposes.
#F represent the quantity of wheat used for direct human consumption as food.

#Now, we can express the given data in the form of a mathematical equation with 3 terms:

#(P+I+V+E)=(DI+AA+S+L+T+AU+F)

#Using the data you provided:

#(38614+2055+1131+21502)=(20298+7822+748+358+1575+2824+6971)

#So, the equation is:

#63462=40396

#### Question 3 : Disponibilité alimentaire (calories, protéines)
Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines. Vous ferez cela à partir de ces informations :
- Population de chaque pays
- Disponibilité alimentaire donnée pour chaque produit et pour chaque pays en kcal/personne/jour, -
- Disponibilité alimentaire en protéines donnée pour chaque produit et pour chaque pays en g/personne/jour.
Pour cette étape vous avez besoin de constituer une seule et même table à partir des tables animaux et végétaux.

In [6]:
# for collect the columns names

'''import pandas as pd

# Load animal and plant data
animal_data = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv')
vegetal_data = pd.read_csv('fao_2013/FAOSTAT_2013_vegetal.csv')

# Merge the animal and plant tables
merged_data = pd.concat([animal_data, vegetal_data], ignore_index=True)

# Display the columns of the merged data
print("Columns in Merged Data:")
print(merged_data.columns)'''

'''import pandas as pd

# Load animal and plant data
animal_data = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv')
vegetal_data = pd.read_csv('fao_2013/FAOSTAT_2013_vegetal.csv')

# Merge the animal and plant tables
 #Concatenate (combine) the animal_data and vegetal_data DataFrames along the rows (axis=0)
# into a new DataFrame called merged_data. The ignore_index=True parameter resets the index of the resulting DataFrame.
merged_data = pd.concat([animal_data, vegetal_data], ignore_index=True)

# Display the columns of the merged data
print("Columns in Merged Data:")
print(merged_data.columns)

# Filter relevant columns
 #Create a list called selected_columns containing the column names 'Pays' (Country), 
#'Produit' (Product), 'Valeur' (Value), and 'Unité' (Unit). These are the columns of interest.
selected_columns = ['Pays', 'Produit', 'Valeur', 'Unité']

#Create a new DataFrame called filtered_data by selecting only the columns specified in the selected_columns 
#list from the merged_data DataFrame.
filtered_data = merged_data[selected_columns]

# Drop rows with missing values
#Remove rows with missing values (NaN) from the filtered_data DataFrame.
filtered_data = filtered_data.dropna()

# Display the filtered data
 #Print a message indicating that the following output will display the filtered data.
print("\nFiltered Data:")
print(filtered_data.head())'''

import pandas as pd

# Load the datasets
# Read the animal, vegetal, and population datasets
animal_data = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv', encoding='latin1')
vegetal_data = pd.read_csv('fao_2013/FAOSTAT_2013_vegetal.csv', encoding='latin1')
population_data = pd.read_csv('fao_2013/FAOSTAT_2013_population_filtered.csv', encoding='latin1')

# Merge animal and vegetal data on common columns
# Concatenate animal and vegetal data along rows to create a unified food_data DataFrame
food_data = pd.concat([animal_data, vegetal_data], ignore_index=True)

# Merge with population data
# Merge the unified food_data DataFrame with the population_data DataFrame on the 'Country Code' column
# Note: Replace 'Country Code' with the actual column name containing country codes in your dataset
# If the column names are different, modify accordingly
merged_data = pd.merge(food_data, population_data, how='inner', on='country Code')

# Calculate availability in kcal and kg of proteins
# Calculate the availability in kilocalories (kcal) and kilograms of proteins for each country and product
# Fill NaN values with 0 to handle missing data
merged_data['Availability_kcal'] = (merged_data['Food supply (kcal/capita/day)'] * merged_data['Population']).fillna(0)
merged_data['Availability_proteins_kg'] = (merged_data['Protein supply quantity (g/capita/day)'] * merged_data['Population'] / 1000).fillna(0)

# Group by country and product to get the total availability
# Group the merged data by 'Country' and 'Item' columns and calculate the sum of availability for each group
total_availability = merged_data.groupby(['Country', 'Item']).agg({
    'Availability_kcal': 'sum',
    'Availability_proteins_kg': 'sum'
}).reset_index()

# Print or export the result as needed
# Display the resulting DataFrame showing total availability of calories and proteins for each country and product
print(total_availability)

KeyError: 'country Code'

#### Question 4 : Ratio énergie/poids
A partir de ces dernières informations, et à partir du poids de la disponibilité alimentaire (pour chaque pays et chaque produit), calculez pour chaque produit le ratio "énergie/poids", que vous donnerez en kcal/kg. Vous pouvez vérifier la cohérence de votre calcul en comparant ce ratio aux données disponibles sur internet, par exemple en cherchant la valeur calorique d'un oeuf.

#### Question 5 : Aliments les plus caloriques et protéiques
En considérant les aliments végétaux et animaux, citez 5 aliments parmi les 20 aliments les plus caloriques, en utilisant le ratio énergie/poids. Citez 5 aliments parmi les 20 aliments les plus riches en protéines.

In [15]:
# annee probem column



import pandas as pd


#These lines of code import the pandas library and load two CSV files ('FAOSTAT_2013_animal.csv' and 'FAOSTAT_2013_vegetal.csv') 
#into DataFrames named animal_data and vegetal_data.
# Load data
animal_data = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv')     
vegetal_data = pd.read_csv('fao_2013/FAOSTAT_2013_vegetal.csv')

# Merge data
#This line merges the two DataFrames (animal_data and vegetal_data) on the specified columns 
#('Code Pays', 'Code Produit', 'Année', 'Unité') using an outer join. The result is stored in a new DataFrame named merged_data.
merged_data = pd.merge(animal_data, vegetal_data, how='outer', on=['Code Pays', 'Code Produit', 'Année', 'Unité'])

# For the 20 most calorically-dense foods
#These lines calculate the energy density for each row by dividing the 'Valeur_x' column 
#(presumably representing energy) by the 'Valeur_y' column (presumably representing weight or quantity). #
#Then, it selects the top 20 rows with the highest energy density and stores them in the DataFrame top_caloric_foods.
merged_data['Energy Density'] = merged_data['Valeur_x'] / merged_data['Valeur_y']
top_caloric_foods = merged_data.sort_values(by='Energy Density', ascending=False).head(20)

# For the 20 foods richest in protein
#These lines select the top 20 rows with the highest values in the 'Valeur_x' column 
#(presumably representing protein content) and stores them in the DataFrame top_protein_foods.top_protein_foods
top_protein_foods = merged_data.sort_values(by='Valeur_x', ascending=False).head(20)


#These lines print the results. The first print statement displays the top 20 most calorically-dense foods with columns 
#'Pays_x', 'Produit_x', and 'Energy Density'. The second print statement displays the top 20 foods richest in protein 
#with columns 'Pays_x', 'Produit_x', and 'Valeur_x'.
# Display the results
print("Top 20 Most Calorically-Dense Foods:")
print(top_caloric_foods[['Pays_x', 'Produit_x', 'Energy Density']])

print("\nTop 20 Foods Richest in Protein:")
print(top_protein_foods[['Pays_x', 'Produit_x', 'Valeur_x']])

Top 20 Most Calorically-Dense Foods:
         Pays_x               Produit_x  Energy Density
0   Afghanistan        Viande de Bovins             NaN
1   Afghanistan        Viande de Bovins             NaN
2   Afghanistan        Viande de Bovins             NaN
3   Afghanistan        Viande de Bovins             NaN
4   Afghanistan        Viande de Bovins             NaN
5   Afghanistan        Viande de Bovins             NaN
6   Afghanistan        Viande de Bovins             NaN
7   Afghanistan        Viande de Bovins             NaN
8   Afghanistan  Viande d'Ovins/Caprins             NaN
9   Afghanistan  Viande d'Ovins/Caprins             NaN
10  Afghanistan  Viande d'Ovins/Caprins             NaN
11  Afghanistan  Viande d'Ovins/Caprins             NaN
12  Afghanistan  Viande d'Ovins/Caprins             NaN
13  Afghanistan  Viande d'Ovins/Caprins             NaN
14  Afghanistan  Viande d'Ovins/Caprins             NaN
15  Afghanistan     Viande de Volailles             NaN
16  Afghanistan     Viande de Volailles             NaN
17  Afghanistan     Viande de Volailles             NaN
18  Afghanistan     Viande de Volailles             NaN
19  Afghanistan     Viande de Volailles             NaN

Top 20 Foods Richest in Protein:
                      Pays_x           Produit_x  Valeur_x
15826                   Inde  Lait - Excl Beurre  135600.0
15830                   Inde  Lait - Excl Beurre  133443.0
15834                   Inde  Lait - Excl Beurre  105807.0
11586  États-Unis d'Amérique  Lait - Excl Beurre   91277.0
11590  États-Unis d'Amérique  Lait - Excl Beurre   87965.0
11594  États-Unis d'Amérique  Lait - Excl Beurre   81513.0
36935                  Chine    Viande de Suides   54730.0
36938                  Chine    Viande de Suides   54689.0
36931                  Chine    Viande de Suides   53752.0
7472     Chine, continentale    Viande de Suides   53268.0
7474     Chine, continentale    Viande de Suides   53247.0
7468     Chine, continentale    Viande de Suides   52733.0
37054                  Chine  Lait - Excl Beurre   50117.0
7577     Chine, continentale  Lait - Excl Beurre   48271.0
37059                  Chine  Lait - Excl Beurre   47009.0
7581     Chine, continentale  Lait - Excl Beurre   45252.0
37050                  Chine  Lait - Excl Beurre   40570.0
7573     Chine, continentale  Lait - Excl Beurre   40193.0
26025               Pakistan  Lait - Excl Beurre   39126.0
26021               Pakistan  Lait - Excl Beurre   39017.0

#### Question 6 : Dispo. intérieure mondiale des végétaux
Calculez, pour les produits végétaux uniquement, la disponibilité intérieure mondiale exprimée en kcal.

In [2]:
'''import pandas as pd

# Read the data
vegetal_data = pd.read_csv('fao_2013/FAOSTAT_2013_vegetal.csv', encoding='latin-1')

# Filter plant products
plant_data = vegetal_data[vegetal_data['Code Domaine'] == 'PML']

# Calculate global domestic availability in kcal
global_domestic_availability_kcal = plant_data['Disponibilité alimentaire (kcal)'].sum()

print(f"Global Domestic Availability of Plant Products in kcal: {global_domestic_availability_kcal:.2f} kcal")'''

import pandas as pd

# Read animal data
#This part of the code reads two CSV files ('FAOSTAT_2013_animal.csv' and 'FAOSTAT_2013_vegetal.csv') 
#into Pandas DataFrames named animal_data and vegetal_data, respectively. 
#The 'encoding' parameter is set to 'latin-1' to handle potential encoding issues.
animal_data = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv', encoding='latin-1')

# Read vegetal data
vegetal_data = pd.read_csv('fao_2013/FAOSTAT_2013_vegetal.csv', encoding='latin-1')

# Display unique values in the 'Année' column for both datasets
print("Unique values in 'Année' column for animal_data:", animal_data['Code Année'].unique())
print("Unique values in 'Année' column for vegetal_data:", vegetal_data['Code Année'].unique())

# Display unique values in the 'Unité' column for both datasets
print("Unique values in 'Unité' column for animal_data:", animal_data['Unité'].unique())
print("Unique values in 'Unité' column for vegetal_data:", vegetal_data['Unité'].unique())

# Merge data on relevant columns
merged_data = pd.merge(animal_data, vegetal_data, how='outer', on=['Code Pays', 'Code Produit', 'Code Année', 'Unité'])

# Select and filter relevant columns
filtered_data = merged_data[['Pays_x', 'Produit_x', 'Population', 'Disponibilité alimentaire (kcal/personne/jour)', 'Disponibilité alimentaire en protéines (g/personne/jour)']].dropna()

# Display the result
print(filtered_data.head())

KeyError: 'Code Année'

#### Question 7 : Potentiel alimentaire des végétaux
Combien d'humains pourraient être nourris si toute la disponibilité intérieure mondiale de produits végétaux était utilisée pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [14]:
import pandas as pd

# Chargement des données
vegetal_file = 'fao_2013/FAOSTAT_2013_vegetal.csv'
vegetal_df = pd.read_csv(vegetal_file)

# Extract and print all column names
column_names = vegetal_df.columns
print("Column Names:")
for column_name in column_names:
    print(column_name)

Column Names:
Code Domaine
Domaine
Code Pays
Pays
Code Élément
Element
Code Produit
Produit
Code Année
Année
Unité
Valeur
Symbole
Description du Symbole

#### Question 8 : Potentiel alimentaire des végétaux (destinés aux animaux pertes)
Combien d'humains pourraient être nourris si toute la disponibilité alimentaire en produits végétaux la nourriture végétale destinée aux animaux et les pertes de produits végétaux étaient utilisés pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [4]:
not finish yet

'''import pandas as pd

# Load the animal products dataset
animal_df = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv')

# Load the cereals dataset
cereal_df = pd.read_csv('fao_2013/FAOSTAT_2013_cereal.csv')

# Display the first few rows of each dataset to get an overview
print("Animal Products Dataset:")
print(animal_df.head())

print("\nCereals Dataset:")
print(cereal_df.head())'''
import pandas as pd

# Load the data from the provided CSV files
vegetal_df = pd.read_csv('fao_2013/FAOSTAT_2013_vegetal.csv')
animal_df = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv')


# Print the column names for vegetal and animal DataFrames
print("Vegetal DataFrame Columns:", vegetal_df.columns)
print("Animal DataFrame Columns:", animal_df.columns)

Vegetal DataFrame Columns: Index(['Code Domaine', 'Domaine', 'Code Pays', 'Pays', 'Code Élément',
       'Element', 'Code Produit', 'Produit', 'Code Année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole'],
      dtype='object')
Animal DataFrame Columns: Index(['Code Domaine', 'Domaine', 'Code Pays', 'Pays', 'Code Élément',
       'Element', 'Code Produit', 'Produit', 'Code Année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole'],
      dtype='object')

#### Question 9 : Potentiel alimentaire de la dispo. Mondiale
Combien d'humains pourraient être nourris avec la disponibilité alimentaire mondiale ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

#### Question 10 : Proportion de la sous-nutrition mondiale
A partir des données téléchargées qui concernent la sous-nutrition, répondez à cette question : Quelle proportion de la population mondiale est considérée comme étant en sous-nutrition ?

#### Question 11 : Céréales
Établissez la liste des produits (ainsi que leur code) considéré comme des céréales selon la FAO. En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), quelle proportion (en termes de poids) est destinée à l'alimentation animale ?

In [14]:
#The code begins by importing the pandas library and giving it the alias pd.
#It then loads the dataset from the 'fao_2013/FAOSTAT_2013_cereal.csv' file using the pd.read_csv function and stores 
#it in a DataFrame named cereal_df.
#The column names of the dataset are then printed to the console.

import pandas as pd

# Load the cereal dataset
cereal_df = pd.read_csv('fao_2013/FAOSTAT_2013_cereal.csv')

# Display the columns in the dataset
print("Cereal Dataset Columns:")
print(cereal_df.columns)


#The code extracts the columns 'Produit' (product) and 'Code Produit' (product code) from the cereal_df DataFrame.
#It then removes duplicate rows to get a list of unique cereal products and their corresponding product codes.
#The result is printed to the console.
# Extract unique cereal products and their codes
cereal_products = cereal_df[['Produit', 'Code Produit']].drop_duplicates()



# Display the list of products considered as cereals
print("\nList of Cereal Products and Their Codes:")
print(cereal_products)


#The code filters the DataFrame to include only rows where the value in the 'Élément' column is 'Nourriture' (food).
#This creates a new DataFrame named cereals_for_food containing cereals intended for food.
# Filter cereals intended for food (human and animal)
cereals_for_food = cereal_df[cereal_df['Élément'] == 'Nourriture']

#The code calculates the total weight of cereals intended for food by summing the 'Valeur' (value) column in the cereals_for_food DataFrame.
#It also calculates the total weight of cereals intended for animal feed by subtracting the total weight for food from the overall total weight.
# Calculate the total weight of cereals intended for food and animal feed
total_weight_for_food = cereals_for_food['Valeur'].sum()
total_weight_for_animal_feed = cereal_df['Valeur'].sum() - total_weight_for_food


#The code calculates the proportion of total weight intended for animal feed as a percentage of the overall total weight.
# Calculate the proportion intended for animal feed
proportion_for_animal_feed = (total_weight_for_animal_feed / cereal_df['Valeur'].sum()) * 100


#The code prints the results, including the total weight of cereals intended for food, total weight for animal feed,
#and the proportion intended for animal feed as a percentage.
# Display the results
print("\nTotal Weight of Cereals Intended for Food:", total_weight_for_food, "kg")
print("Total Weight of Cereals Intended for Animal Feed:", total_weight_for_animal_feed, "kg")
print("Proportion Intended for Animal Feed:", proportion_for_animal_feed, "%")

Cereal Dataset Columns:
Index(['Code Domaine', 'Domaine', 'Code Pays', 'Pays', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code Année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole'],
      dtype='object')

List of Cereal Products and Their Codes:
              Produit  Code Produit
0                 Blé          2511
11   Riz (Eq Blanchi)          2805
21               Orge          2513
33               Maïs          2514
45             Millet          2517
54   Céréales, Autres          2520
116            Seigle          2515
129            Avoine          2516
153            Sorgho          2518

Total Weight of Cereals Intended for Food: 1241405.0 kg
Total Weight of Cereals Intended for Animal Feed: 8535543.459999999 kg
Proportion Intended for Animal Feed: 87.30273556131644 %

#### Question 12 : Sous-nutrition
Sélectionnez parmi les données des bilans alimentaires les informations relatives aux pays dans lesquels la FAO recense des personnes en sous-nutrition.
Repérez les 15 produits les plus exportés par ce groupe de pays.
Parmi les données des bilans alimentaires au niveau mondial, sélectionnez les 200 plus grandes importations de ces produits (1 importation = une quantité d'un produit donné importée par un pays donné).
Groupez ces importations par produit, afin d'avoir une table contenant 1 ligne pour chacun des 15 produits. Ensuite, calculez pour chaque produit les 2 quantités suivantes :

    • le ratio entre la quantité destinés aux "Autres utilisations" (Other uses) et la disponibilité intérieure.
    • le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)
    
Donnez les 3 produits qui ont la plus grande valeur pour chacun des 2 ratios (vous aurez donc 6 produits à citer)

#### Question 13 : USA
Combien de tonnes de céréales pourraient être libérées si les USA diminuaient leur production de produits animaux de 10% ?

In [12]:
import pandas as pd

# Load the animal dataset
animal_df = pd.read_csv('fao_2013/FAOSTAT_2013_animal.csv')

#this prints a message and the names of all columns present in the Animal Dataset. It helps you understand the structure of the dataset.
# Display the available columns in the Animal Dataset
print("Columns in the Animal Dataset:")
print(animal_df.columns)

#This line creates a new DataFrame called animal_df_filtered by selecting
#specific columns ('Pays', 'Produit', 'Code Année', 'Année', 'Unité', 'Valeur') from the original animal_df.
# Based on the available columns, select the relevant ones
animal_df_filtered = animal_df[['Pays', 'Produit', 'Code Année', 'Année', 'Unité', 'Valeur']]

#This line creates a new DataFrame called animal_usa by filtering rows where the 'Pays' (Country) column 
#is equal to 'États-Unis d'Amérique' (United States of America).
# Filter data for the USA
animal_usa = animal_df_filtered[animal_df_filtered['Pays'] == 'États-Unis d\'Amérique']

# Display the filtered data
print("\nFiltered Animal Data for the USA:")
print(animal_usa)

Columns in the Animal Dataset:
Index(['Code Domaine', 'Domaine', 'Code Pays', 'Pays', 'Code Élément',
       'Element', 'Code Produit', 'Produit', 'Code Année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole'],
      dtype='object')

Filtered Animal Data for the USA:
                        Pays             Produit  Code Année  Année  \
11447  États-Unis d'Amérique    Viande de Bovins        2013   2013
11448  États-Unis d'Amérique    Viande de Bovins        2013   2013
11449  États-Unis d'Amérique    Viande de Bovins        2013   2013
11450  États-Unis d'Amérique    Viande de Bovins        2013   2013
11451  États-Unis d'Amérique    Viande de Bovins        2013   2013
...                      ...                 ...         ...    ...
11696  États-Unis d'Amérique  Plantes Aquatiques        2013   2013
11697  États-Unis d'Amérique  Plantes Aquatiques        2013   2013
11698  États-Unis d'Amérique  Plantes Aquatiques        2013   2013
11699  États-Unis d'Amérique  Plantes Aquatiques        2013   2013
11700  États-Unis d'Amérique  Plantes Aquatiques        2013   2013

                    Unité   Valeur
11447  Milliers de tonnes  11719.0
11448  Milliers de tonnes   1113.0
11449  Milliers de tonnes      0.0
11450  Milliers de tonnes   1245.0
11451  Milliers de tonnes  11587.0
...                   ...      ...
11696  Milliers de tonnes      0.0
11697                  kg      0.0
11698  Kcal/personne/jour      0.0
11699     g/personne/jour      0.0
11700     g/personne/jour      0.0

[254 rows x 6 columns]

#### Question 14 : Thaïlande
En Thaïlande, quelle proportion de manioc est exportée ? Quelle est la proportion de personnes en sous-nutrition?

In [3]:
import pandas as pd

# Load the vegetal dataset
vegetal_data = pd.read_csv('fao_2013/FAOSTAT_2013_vegetal.csv', encoding='latin1')

# Filter data for Thailand and Cassava
thailand_cassava = vegetal_data[(vegetal_data['Pays'] == 'Thailand') & (vegetal_data['Item'] == 'Cassava')]

# Calculate the proportion of cassava exported in Thailand
# Proportion of cassava exported = (Export Quantity / Production Quantity) * 100
proportion_exported = (thailand_cassava['Export Quantity'] / thailand_cassava['Production']).iloc[0] * 100

# Print the result
print(f"The proportion of Cassava exported in Thailand: {proportion_exported:.2f}%")

# Note: The 'Undernourishment' column indicates the proportion of people in undernourishment.
# You can use this information directly.
undernourishment_thailand = vegetal_data[vegetal_data['Pays'] == 'Thailand']['Undernourishment'].iloc[0]
print(f"The proportion of people in undernourishment in Thailand: {undernourishment_thailand:.2f}%")

KeyError: 'Item'

### 3 - Etude guidée n°2

Il s’agit ici d’intégrer toutes les données dans une base de données relationnelle puis de répondre à toutes les questions ci-dessous.
La base de données contiendra 4 tables : population, dispo_alim, equilibre_prod, sous_nutrition.

#### Question 15 : Table population
Définir une clé primaire pertinente pour la table population. Intégrer la table dans la base de données relationnelle.

#### Question 16 : Table dispo_alim
La table appelée dispo_alim contient pour chaque pays, pour chaque produit, sur l'année 2013, les informations suivantes:
- la nature du produit (deux valeurs possibles“animal” ou “végétal”)
- disponibilité alimentaire en tonnes
- disponibilité alimentaire en Kcal/personne/jour
- disponibilité alimentaire de protéines en g/personne/jour
- disponibilité alimentaire de matières grasses en g/personne/jour
La table contient ces colonnes : pays, code_pays, année, produit, code_produit, origin, dispo_alim_tonnes, dispo_alim_kcal_p_j, dispo_prot, dispo_mat_gr .
Définir une clé primaire pertinente pour la table dispo_alim. Intégrer la table dans la base de données relationnelle.

#### Question 17 : Table equilibre_prod
La table appelée equilibre_prod contient pour chaque pays, pour chaque produit, et pour l'année disponible 2013, les quantités suivantes :
- disponibilité intérieure
- aliments pour animaux
- semences
- pertes
- transformés
- nourriture
- autres utilisations
Elle contient ces colonnes : pays, code_pays, année, produit, code_produit, dispo_int, alim_ani, semences, pertes, transfo, nourriture, autres_utilisations.
Définir une clé primaire pertinente pour la table equilibre_prod. Intégrer la table dans la base de données relationnelle.

#### Question 18 : Table sous_nutrition
La table appelée sous_nutrition, contient le nombre de personnes en sous-alimentation pour chaque pays et pour chaque année. Elle contient 4 colonnes : pays, code_pays, année, nb_personnes.
Définir une clé primaire pertinente pour la table sous_nutrition. Intégrer la table dans la base de données relationnelle.

#### Question 19 : Requêtes SQL
Formuler les requêtes SQL pour répondre aux questions suivantes :
    • Quels sont les 10 pays ayant le plus haut ratio disponibilité alimentaire/habitant en termes de protéines (en kg) par habitant, puis en termes de kcal par habitant ?
    • Quels sont les 10 pays ayant le plus faible ratio disponibilité alimentaire/habitant en termes de protéines (en kg) par habitant ?
    • Quelle est la quantité totale (en kg) de produits perdus par pays?
    • Quels sont les 10 pays pour lesquels la proportion de personnes sous-alimentées est la plus forte ?
    • Quels sont les 10 produits pour lesquels le ratio Autres utilisations/Disponibilité intérieure est le plus élevé ?

#### Question 20 : Autres utilisations des produits
Pour quelques-uns des produits identifiés dans cette dernière requête SQL, supposez quelles sont ces "autres utilisations" possibles (recherchez sur internet !).

ModuleNotFoundError: No module named 'panda'

### 4 - Analyses complémentaire

Fort de votre expérience de Data Analyst, il s’agit maintenant de réaliser vos propres analyses et exploration.